### ISSUE TITLE
Hard Cider

### ISSUE THREAD

**Issue by lsi5974** [Tieso2001/BoneAppleTea#10]
After all those apples from your apple orchard (courtesy of Pams HarvestCraft apple trees) its time to put your fruit press to work and make us some apple cider.  Once we have the cider, fill a pot on the stove with it (6 cider) and add 3 honey.  Once the honey is dissolved you will have sweetened cider, place the sweetened cider in the fermenting barrel, let it cool and add 1 brewers/wine yeast, allow the liquid to ferment for 2 days (2 weeks irl), allow another day (week irl) to settle the old yeast particles.  (irl the liquid would be siphoned off to a secondary carboy to age some more, leaving the yeast sediment behind.)  The fermenting cider is left for another 2 days (2 weeks) to age into hard cider.  At this point the hard cider can be bottled or it can sit some more to gain potency.   If it is left to age for 8 days after becoming hard cider it ages into aged(fizzy) hard cider.  A third option is to place a pot on the stove with 1 water and 1 honey to make honey water.  Place the honey water into a fermentation barrel and add the finished hard cider from the previous fermentation barrel.  Once the liquids are combined into sparkling cider mix allow it to ferment for another day.  Bottle after the sparkling cider fermentation is done. (irl you bottle immediately after combining the two liquids.)  Allow the bottles to sit 2 more days to insure proper fermentation.

**Comment by Tieso2001** [comment]
#19
