### ISSUE TITLE
Happy meals.

### ISSUE THREAD

**Issue by lsi5974** [Tieso2001/BoneAppleTea#16]
All mods have separate dishes, cooked pork chops, cooked chicken, bacon, etc, etc, and each one provides a small amount of food and saturation, but what if you ate an entire meal at one time, instead of each piece over and over.  In the workbench place a tray or bag or box or whatever, add a balanced blend of proteins, carbohydrates, veggies, fruit and something to drink, alcoholic or otherwise and package it up for a boxed, bagged, complete or whatever meal.  The meals food and saturation could be a little better than the individual foods themselves just because its a well balanced meal and if you really wanted and the meal filled the food bar at max health, you could grant a small buff of some kind or an increased saturation or something similar indicating what a filling, healthy, rounded meal just eaten.  An example meal could be a ham sandwich, green beans, an apple and some moonshine, which would be a fairly healthy meal, replace the moonshine with milk and youve got a very healthy meal, throw something less healthy in there, moonshine and candy instead of an apple and youve got a meal or not so healthy meal, all eaten at one  time.  The meals have varying sizes based on assigned food values or abstract numbers based on the size of the food item or maybe a nutritional value, etc.  The size/nutritional value of the meal determines the amount of food shanks, saturation restored and what buff or how significant of a buff is received.

**Comment by Tieso2001** [comment]
I will add combining different food items to create a (larger) meal/food item, but I wont add a happy meal or some box or bag item as food.

**Comment by lsi5974** [comment]
Cool, it doesnt really matter what they are combined into a container or on a plate, just so the meal can be eaten all at once instead of piece by piece, packaging doesnt really make a difference.  The different sizes were just a way to stop the easy, small food stuffs always being used to make the meals.  It is also a way to encourage actual cooking different food stuffs to heal different shank amounts and saturation and a single large meal would cover that and everything in-between, the only concern Id have with that would be an average amount of shanks, the middle shanks.  If a person were at half shanks would they wait til they were a little more hungry so they could eat the big meal without wasting anything, or would they just eat multiple steaks again, which would pretty much defeat the purpose of the meals or course this all depends on which mods were used with this.  Might want to add a "Best played with" section someplace on your mod page somewhere, maybe mods like Pam's HC, and apple skin I think it is or apple core, one of them, but mods like that.  The meals themselves wouldnt even have to be box lunches or happy meals, maybe just a plate and the different sizes could be named breakfast, lunch, brunch, dinner or supper, depending where you are from.  Or you could just skip them totally, lol, just some neurons passing through my synapses.  

Lol, just realized I called the suggestion happy meals, not what I meant, just meals that make people happy cuz they dont have to keep eating smaller portions.

**Comment by lsi5974** [comment]
Still here and following :-)... definitely not stalking...  A mod called Well Fed kind of does what I was aiming for here, except not with all the other potion benefits, just the shanks and staving off hunger longer portion of it.
