### ISSUE TITLE
Apple Juice

### ISSUE THREAD

**Issue by Tieso2001** [Tieso2001/BoneAppleTea#18]
- [x] Apple Juice Fluid

- [x] Apple Fluid Bucket 

Fluid is created by putting apples into a fruit press.

**Comment by Tieso2001** [comment]
e4ab130d5f605054879faa37b5a4ea439b1324a8

**Comment by Z3r0byte** [comment]
![](https://media.tenor.com/images/c4fdc1b5d21c741e5ef4bc649678d29c/tenor.gif)
